# Generated by Django 6.0.6 on 2026-08-16 11:55

import django.db.models.deletion
import product.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_shipmentlog_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='تاریخ دقیق تعطیلی (میلادی)', unique=True, verbose_name='تاریخ میلادی')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='مناسبت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تعطیلی',
                'verbose_name_plural': 'تعطیلات',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='PaintingProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام روند')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد روند')),
                ('color_codes', models.JSONField(default=list, verbose_name='لیست کدهای رنگی مرتبط')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'روند نقاشی',
                'verbose_name_plural': 'روندهای نقاشی',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='due_date',
            field=product.fields.PersianDateField(blank=True, null=True, verbose_name='تاریخ تحویل'),
        ),
        migrations.AddField(
            model_name='order',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 'بسیار بالا'), (2, 'بالا'), (3, 'متوسط'), (4, 'پایین')], default=3, verbose_name='اولویت'),
        ),
        migrations.AddField(
            model_name='productiontask',
            name='assigned_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='کارگر تخصیص\u200cیافته'),
        ),
        migrations.AddField(
            model_name='productiontask',
            name='color_part',
            field=models.CharField(blank=True, max_length=50, verbose_name='بخش رنگی (بدنه، درب، ...)'),
        ),
        migrations.AddField(
            model_name='productiontask',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paint_tasks', to='product.orderitem', verbose_name='آیتم سفارش مرتبط (برای نقاشی)'),
        ),
        migrations.AddField(
            model_name='productiontask',
            name='scheduled_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان برنامه\u200cریزی شده'),
        ),
        migrations.AddField(
            model_name='productiontask',
            name='scheduled_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع برنامه\u200cریزی شده'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='excluded_items',
            field=models.ManyToManyField(blank=True, help_text='کارگر روی این آیتم\u200cهای خاص کار نخواهد کرد', to='product.orderitem', verbose_name='آیتم\u200cهای ممنوعه'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='excluded_products',
            field=models.ManyToManyField(blank=True, help_text='کارگر در زمان\u200cبندی این محصولات لحاظ نمی\u200cشود', to='product.product', verbose_name='محصولات ممنوعه'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='فعال برای زمان\u200cبندی'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='skill_costs',
            field=models.JSONField(blank=True, default=dict, verbose_name='اولویت ترجیحی مهارت\u200cها'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='skills',
            field=models.JSONField(blank=True, default=list, verbose_name='مهارت\u200cها (لیست رشته\u200cها)'),
        ),
        migrations.AlterField(
            model_name='productiontask',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.part', verbose_name='قطعه'),
        ),
        migrations.AlterField(
            model_name='productiontask',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='عدد قطعه'),
        ),
        migrations.AlterField(
            model_name='productiontask',
            name='status',
            field=models.CharField(choices=[('waiting', 'در انتظار مرحله قبل'), ('pending', 'آماده انجام'), ('done', 'تکمیل شده')], default='waiting', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.CreateModel(
            name='PaintingStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(verbose_name='ترتیب مرحله')),
                ('name', models.CharField(max_length=100, verbose_name='نام مرحله')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='زمان انجام (دقیقه)')),
                ('drying_time_minutes', models.PositiveIntegerField(default=0, verbose_name='زمان خشک\u200cشدن (دقیقه)')),
                ('required_skill', models.CharField(choices=[('painter', 'نقاش'), ('general', 'زیرکار')], default='painter', max_length=50, verbose_name='مهارت مورد نیاز')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='product.paintingprocess')),
            ],
            options={
                'verbose_name': 'مرحله نقاشی',
                'verbose_name_plural': 'مراحل نقاشی',
                'ordering': ['process', 'order'],
                'unique_together': {('process', 'order')},
            },
        ),
        migrations.CreateModel(
            name='PaintingAssignmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_codes', models.JSONField(blank=True, help_text='لیست کدهای رنگی که این قانون برای آن\u200cها اعمال می\u200cشود (خالی = همه رنگ\u200cها)', null=True, verbose_name='کدهای رنگ')),
                ('priority', models.IntegerField(default=100, help_text='عدد بالاتر = اولویت بیشتر در زمان\u200cبندی', verbose_name='اولویت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_rules', to='product.workerprofile', verbose_name='کارگر')),
                ('process', models.ForeignKey(blank=True, help_text='محدود کردن مرحله به یک روند خاص', null=True, on_delete=django.db.models.deletion.CASCADE, to='product.paintingprocess', verbose_name='روند نقاشی (اختیاری)')),
                ('painting_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.paintingstage', verbose_name='مرحله نقاشی (اختیاری)')),
            ],
            options={
                'verbose_name': 'قانون تخصیص کارگر',
                'verbose_name_plural': 'قوانین تخصیص کارگر',
                'ordering': ['-priority', 'worker'],
            },
        ),
        migrations.AddField(
            model_name='productiontask',
            name='painting_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.paintingstage', verbose_name='مرحله نقاشی'),
        ),
    ]
