# Generated by Django 6.0.6 on 2026-08-19 12:08

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_holiday_paintingprocess_order_due_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerprofile',
            name='skill_costs',
        ),
        migrations.AddField(
            model_name='paintingassignmentrule',
            name='rule_type',
            field=models.CharField(choices=[('priority', 'فقط اولویت\u200cدهی'), ('exclusive', 'محدودکننده'), ('exclusion', 'منع\u200cکننده')], default='priority', help_text='فقط اولویت\u200cدهی، محدودکننده (کارگر فقط همین تسک\u200cها را بگیرد) یا منع\u200cکننده', max_length=20, verbose_name='نوع قانون'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='break_end',
            field=models.TimeField(default=datetime.time(13, 30), verbose_name='پایان استراحت'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='break_start',
            field=models.TimeField(default=datetime.time(12, 30), verbose_name='شروع استراحت'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='skill_priority',
            field=models.JSONField(blank=True, default=dict, verbose_name='اولویت/میزان مهارت کارگر'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='work_end',
            field=models.TimeField(default=datetime.time(16, 30), verbose_name='پایان کار'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='work_start',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name='شروع کار'),
        ),
        migrations.AlterField(
            model_name='paintingassignmentrule',
            name='priority',
            field=models.IntegerField(default=100, help_text='عدد بالاتر = اولویت بیشتر در زمان\u200cبندی (فقط برای نوع اولویت\u200cدهی)', verbose_name='اولویت'),
        ),
        migrations.AddIndex(
            model_name='productiontask',
            index=models.Index(fields=['station_name', 'scheduled_start'], name='product_pro_station_483d1d_idx'),
        ),
        migrations.AddIndex(
            model_name='productiontask',
            index=models.Index(fields=['assigned_worker', 'scheduled_start'], name='product_pro_assigne_824415_idx'),
        ),
        migrations.AddIndex(
            model_name='productiontask',
            index=models.Index(fields=['order_item', 'station_name', 'status'], name='product_pro_order_i_cb6f35_idx'),
        ),
    ]
