# Generated by Django 5.2.11 on 2026-09-13 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_workerprofile_skill_costs_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='consumption_per_unit',
            field=models.DecimalField(decimal_places=3, default=1, help_text='مقدار مصرف به ازای هر قطعه', max_digits=10, verbose_name='مقدار مصرف به ازای هر قطعه'),
        ),
        migrations.AddField(
            model_name='productiontask',
            name='completed_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد انجام\u200cشده'),
        ),
        migrations.AddField(
            model_name='shipmentlog',
            name='delivery_notes',
            field=models.TextField(blank=True, verbose_name='یادداشت\u200cهای تحویل'),
        ),
migrations.CreateModel(
            name='ProductionDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد خراب')),
                ('description', models.TextField(verbose_name='شرح خرابی و اقدام لازم')),
                ('status', models.CharField(choices=[('reported', 'ثبت شده'), ('material_requested', 'در انتظار مواد جایگزین'), ('rework_issued', 'مواد جایگزین تحویل شد'), ('closed', 'بسته شده')], default='reported', max_length=30, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='product.order', verbose_name='سفارش')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defects', to='product.orderitem', verbose_name='آیتم سفارش')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defects', to='product.part', verbose_name='قطعه آسیب\u200cدیده')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_defects', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defects', to='product.productiontask', verbose_name='مرحله/تسک')),
            ],
            options={
                'verbose_name': 'خرابی تولید',
                'verbose_name_plural': 'خرابی\u200cهای تولید',
                'ordering': ['-created_at'],
            },
        ),
    ]
