# Generated by Django 5.2.11 on 2026-09-16 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '__first__'),
        ('product', '0005_remove_workerprofile_skill_costs_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='consumption_per_unit',
            field=models.DecimalField(decimal_places=3, default=1, help_text='مقدار مصرف به ازای هر قطعه', max_digits=10, verbose_name='مقدار مصرف به ازای هر قطعه'),
        ),
        migrations.AddField(
            model_name='material',
            name='raw_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_materials', to='inventory.rawmaterial', verbose_name='ماده اولیه انبار (برای مصرف خودکار)'),
        ),
        migrations.AddField(
            model_name='productiontask',
            name='completed_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد انجام\u200cشده'),
        ),
        migrations.AddField(
            model_name='shipmentlog',
            name='delivery_notes',
            field=models.TextField(blank=True, verbose_name='یادداشت\u200cهای تحویل'),
        ),
        migrations.CreateModel(
            name='PaintingProcessMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_color_variant', models.BooleanField(default=False, help_text='اگر فعال باشد، جنس واقعی ماده بر اساس کد رنگ سفارش انتخاب می\u200cشود؛ مقدار مصرف در PaintingMaterialRequirement ثابت می\u200cماند.', verbose_name='وابسته به کد رنگ سفارش')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_materials', to='product.paintingprocess', verbose_name='روند نقاشی')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_catalog_entries', to='inventory.rawmaterial', verbose_name='مادة اولیه')),
            ],
            options={
                'verbose_name': 'ماده اولیه کاتالوگ روند',
                'verbose_name_plural': 'مواد اولیه کاتالوگ روندها',
                'ordering': ['process__name', 'raw_material__name'],
                'unique_together': {('process', 'raw_material')},
            },
        ),
        migrations.CreateModel(
            name='ProductionDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_part', models.CharField(blank=True, choices=[('بدنه', 'بدنه'), ('درب', 'درب'), ('دستگیره', 'دستگیره'), ('پایه', 'پایه'), ('صفحه', 'صفحه'), ('رینگ', 'رینگ')], max_length=20, verbose_name='بخش رنگی')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد خراب')),
                ('description', models.TextField(verbose_name='شرح خرابی و اقدام لازم')),
                ('status', models.CharField(choices=[('reported', 'ثبت شده'), ('material_requested', 'در انتظار مواد جایگزین'), ('rework_issued', 'مواد جایگزین تحویل شد'), ('closed', 'بسته شده')], default='reported', max_length=30, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='product.order', verbose_name='سفارش')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defects', to='product.orderitem', verbose_name='آیتم سفارش')),
                ('packaging_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defects', to='product.packagingunit', verbose_name='واحد بسته\u200cبندی (بارکد یکتا)')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defects', to='product.part', verbose_name='قطعه آسیب\u200cدیده')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_defects', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defects', to='product.productiontask', verbose_name='مرحله/تسک (اختیاری)')),
            ],
            options={
                'verbose_name': 'خرابی تولید',
                'verbose_name_plural': 'خرابی\u200cهای تولید',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaintingMaterialRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_part', models.CharField(choices=[('بدنه', 'بدنه'), ('درب', 'درب'), ('دستگیره', 'دستگیره'), ('پایه', 'پایه'), ('صفحه', 'صفحه'), ('رینگ', 'رینگ')], max_length=20, verbose_name='بخش رنگی')),
                ('consumption_per_unit', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='مقدار مصرف به ازای هر واحد محصول')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_requirements', to='product.paintingprocess', verbose_name='روند نقاشی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='painting_material_requirements', to='product.product', verbose_name='محصول')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='painting_requirements', to='inventory.rawmaterial', verbose_name='مادة اولیه')),
            ],
            options={
                'verbose_name': 'فرمول مصرف مواد نقاشی',
                'verbose_name_plural': 'فرمول\u200cهای مصرف مواد نقاشی',
                'ordering': ['product__name', 'color_part', 'process__name', 'raw_material__name'],
                'unique_together': {('process', 'raw_material', 'product', 'color_part')},
            },
        ),
        migrations.CreateModel(
            name='PaintingColorMaterialVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_code', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('جناغی', 'جناغی'), ('بتنی', 'بتنی')], max_length=20, verbose_name='کد رنگ سفارش')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='painting_color_variants', to='inventory.rawmaterial', verbose_name='ماده اولیه واقعی')),
                ('process_material', models.ForeignKey(limit_choices_to={'is_color_variant': True}, on_delete=django.db.models.deletion.CASCADE, related_name='color_variants', to='product.paintingprocessmaterial', verbose_name='اسلات ماده کاتالوگ روند')),
            ],
            options={
                'verbose_name': 'نگاشت کد رنگ به ماده اولیه',
                'verbose_name_plural': 'نگاشت\u200cهای کد رنگ به ماده اولیه',
                'ordering': ['process_material__process__name', 'process_material__raw_material__name', 'color_code'],
                'unique_together': {('process_material', 'color_code')},
            },
        ),
        migrations.CreateModel(
            name='ProductionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(choices=[('cut', 'برش'), ('cnc', 'CNC'), ('dr', 'سوراخکاری'), ('pvc', 'نوارکاری'), ('prs', 'پرس'), ('mon', 'مونتاژ اول'), ('vacum', 'وکیوم'), ('paint', 'نقاشی'), ('assembly2', 'مونتاژ نهایی'), ('packaging', 'بسته\u200cبندی'), ('shipping', 'ارسال شده')], max_length=50, verbose_name='ایستگاه')),
                ('event_type', models.CharField(choices=[('started', 'شروع'), ('done', 'اتمام'), ('reassigned', 'تغییر کارگر'), ('status_changed', 'تغییر وضعیت دستی')], max_length=20, verbose_name='نوع رویداد')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='تعداد در این رویداد')),
                ('old_status', models.CharField(blank=True, max_length=20, verbose_name='وضعیت قبلی')),
                ('new_status', models.CharField(blank=True, max_length=20, verbose_name='وضعیت جدید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('new_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='کارگر جدید')),
                ('old_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='کارگر قبلی')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_events', to='product.order', verbose_name='سفارش')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_events', to='product.orderitem', verbose_name='آیتم سفارش')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='product.productiontask', verbose_name='تسک تولید')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
            ],
            options={
                'verbose_name': 'رویداد تولید',
                'verbose_name_plural': 'رویدادهای تولید',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order_item', 'station_name'], name='product_pro_order_i_77e230_idx'), models.Index(fields=['task', 'created_at'], name='product_pro_task_id_9f4fbd_idx'), models.Index(fields=['event_type', 'created_at'], name='product_pro_event_t_828514_idx')],
            },
        ),
    ]
