# Generated by Django 5.2.11 on 2026-09-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_material_consumption_per_unit_material_raw_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productiontask',
            name='custom_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='عنوان دلخواه'),
        ),
        migrations.AddField(
            model_name='productiontask',
            name='custom_duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مدت زمان دلخواه (دقیقه)'),
        ),
        migrations.AddField(
            model_name='productiontask',
            name='custom_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='یادداشت دلخواه'),
        ),
    ]