# Generated by Django 5.2.11 on 2026-09-13 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('product', '0006_material_consumption_per_unit_material_raw_material_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='raw_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_materials', to='inventory.rawmaterial', verbose_name='ماده اولیه انبار (برای مصرف خودکار)'),
        ),
        migrations.CreateModel(
            name='PaintingMaterialRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_part', models.CharField(choices=[('بدنه', 'بدنه'), ('درب', 'درب'), ('دستگیره', 'دستگیره'), ('پایه', 'پایه'), ('صفحه', 'صفحه'), ('رینگ', 'رینگ')], max_length=20, verbose_name='بخش رنگی')),
                ('consumption_per_unit', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='مقدار مصرف به ازای هر واحد محصول')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_requirements', to='product.paintingprocess', verbose_name='روند نقاشی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='painting_material_requirements', to='product.product', verbose_name='محصول')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='painting_requirements', to='inventory.rawmaterial', verbose_name='مادة اولیه')),
            ],
            options={
                'verbose_name': 'فرمول مصرف مواد نقاشی',
                'verbose_name_plural': 'فرمول\u200cهای مصرف مواد نقاشی',
                'ordering': ['product__name', 'color_part', 'process__name', 'raw_material__name'],
                'unique_together': {('process', 'raw_material', 'product', 'color_part')},
            },
        ),
        migrations.CreateModel(
            name='PaintingProcessMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_materials', to='product.paintingprocess', verbose_name='روند نقاشی')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_catalog_entries', to='inventory.rawmaterial', verbose_name='مادة اولیه')),
            ],
            options={
                'verbose_name': 'ماده اولیه کاتالوگ روند',
                'verbose_name_plural': 'مواد اولیه کاتالوگ روندها',
                'ordering': ['process__name', 'raw_material__name'],
                'unique_together': {('process', 'raw_material')},
            },
        ),
        migrations.CreateModel(
            name='ProductionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(choices=[('cut', 'برش'), ('cnc', 'CNC'), ('dr', 'سوراخکاری'), ('pvc', 'نوارکاری'), ('prs', 'پرس'), ('mon', 'مونتاژ اول'), ('vacum', 'وکیوم'), ('paint', 'نقاشی'), ('assembly2', 'مونتاژ نهایی'), ('packaging', 'بسته\u200cبندی'), ('shipping', 'ارسال شده')], max_length=50, verbose_name='ایستگاه')),
                ('event_type', models.CharField(choices=[('started', 'شروع'), ('done', 'اتمام'), ('reassigned', 'تغییر کارگر'), ('status_changed', 'تغییر وضعیت دستی')], max_length=20, verbose_name='نوع رویداد')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='تعداد در این رویداد')),
                ('old_status', models.CharField(blank=True, max_length=20, verbose_name='وضعیت قبلی')),
                ('new_status', models.CharField(blank=True, max_length=20, verbose_name='وضعیت جدید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('new_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='کارگر جدید')),
                ('old_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='کارگر قبلی')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_events', to='product.order', verbose_name='سفارش')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_events', to='product.orderitem', verbose_name='آیتم سفارش')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='product.productiontask', verbose_name='تسک تولید')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
            ],
            options={
                'verbose_name': 'رویداد تولید',
                'verbose_name_plural': 'رویدادهای تولید',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order_item', 'station_name'], name='product_pro_order_i_77e230_idx'), models.Index(fields=['task', 'created_at'], name='product_pro_task_id_9f4fbd_idx'), models.Index(fields=['event_type', 'created_at'], name='product_pro_event_t_828514_idx')],
            },
        ),
    ]