# Generated by Django 5.2.11 on 2026-09-13 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('product', '0007_material_raw_material_paintingmodels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paintingprocessmaterial',
            name='is_color_variant',
            field=models.BooleanField(default=False, help_text='اگر فعال باشد، جنس واقعی ماده بر اساس کد رنگ سفارش انتخاب می\u200cشود؛ مقدار مصرف در PaintingMaterialRequirement ثابت می\u200cماند.', verbose_name='وابسته به کد رنگ سفارش'),
        ),
        migrations.CreateModel(
            name='PaintingColorMaterialVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_code', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('جناغی', 'جناغی'), ('بتنی', 'بتنی')], max_length=20, verbose_name='کد رنگ سفارش')),
                ('process_material', models.ForeignKey(limit_choices_to={'is_color_variant': True}, on_delete=django.db.models.deletion.CASCADE, related_name='color_variants', to='product.paintingprocessmaterial', verbose_name='اسلات ماده کاتالوگ روند')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='painting_color_variants', to='inventory.rawmaterial', verbose_name='ماده اولیه واقعی')),
            ],
            options={
                'verbose_name': 'نگاشت کد رنگ به ماده اولیه',
                'verbose_name_plural': 'نگاشت\u200cهای کد رنگ به ماده اولیه',
                'ordering': ['process_material__process__name', 'process_material__raw_material__name', 'color_code'],
                'unique_together': {('process_material', 'color_code')},
            },
        ),
    ]
