# Generated by Django 5.2.11 on 2026-09-14 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_defect_by_order_and_colorpart'),
    ]

    operations = [
        migrations.AddField(
            model_name='productiondefect',
            name='packaging_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defects', to='product.packagingunit', verbose_name='واحد بسته\u200cبندی (بارکد یکتا)'),
        ),
    ]
