# Generated by Django 5.2.11 on 2026-09-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_backfill_color_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='بارکد محصول'),
        ),
        migrations.AddField(
            model_name='product',
            name='package_quantity',
            field=models.PositiveIntegerField(default=1, help_text='تعداد واحدهای موجود در هر بسته/قوطی خریداری شده', verbose_name='تعداد در هر بسته'),
        ),
    ]
