# Generated by Django 5.2.11 on 2026-09-19 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_add_barcode_package_quantity_to_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='product',
            name='package_quantity',
        ),
    ]
