# Generated by Django 5.2.11 on 2026-09-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_product_barcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد رنگ')),
                ('hex_code', models.CharField(blank=True, max_length=7, verbose_name='کد هگز رنگ')),
                ('material_name', models.CharField(blank=True, max_length=50, verbose_name='نام متریال پیش\u200cفرض')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'تعریف کد رنگ',
                'verbose_name_plural': 'تعریف\u200cهای کد رنگ',
            },
        ),
    ]
