# Generated by Django 5.2.11 on 2026-09-20 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_seed_color_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productiontask',
            name='order',
            field=models.ForeignKey(blank=True, help_text='خالی = کارت دلخواه نقاشی (بدون سفارش)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='product.order', verbose_name='سفارش'),
        ),
    ]
