# Generated by Django 5.2.11 on 2026-09-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_productiontask_order_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='code',
            field=models.CharField(max_length=20, verbose_name='کد رنگ'),
        ),
        migrations.AlterField(
            model_name='paintingcolormaterialvariant',
            name='color_code',
            field=models.CharField(max_length=20, verbose_name='کد رنگ سفارش'),
        ),
    ]
