# Generated by Django 5.2.11 on 2026-09-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_material_consumption_per_unit_material_raw_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentlog',
            name='delivery_notes',
            field=models.TextField(blank=True, verbose_name='یادداشت\u200cهای تحویل'),
        ),
    ]
