# Generated by Django 5.2.11 on 2026-09-10 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_shipmentlog_delivery_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد خراب')),
                ('description', models.TextField(verbose_name='شرح خرابی و اقدام لازم')),
                ('status', models.CharField(choices=[('reported', 'ثبت شده'), ('material_requested', 'در انتظار مواد جایگزین'), ('rework_issued', 'مواد جایگزین تحویل شد'), ('closed', 'بسته شده')], default='reported', max_length=30, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='product.order', verbose_name='سفارش')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defects', to='product.orderitem', verbose_name='آیتم سفارش')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defects', to='product.part', verbose_name='قطعه آسیب\u200cدیده')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_defects', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defects', to='product.productiontask', verbose_name='مرحله/تسک')),
            ],
            options={
                'verbose_name': 'خرابی تولید',
                'verbose_name_plural': 'خرابی\u200cهای تولید',
                'ordering': ['-created_at'],
            },
        ),
    ]
