# Generated by Django 5.2.11 on 2026-10-05 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_custodyconsumption_custody_return_and_more'),
        ('product', '0018_productcategory_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productiondefect',
            name='material_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='مقدار مادهٔ جایگزین'),
        ),
        migrations.AddField(
            model_name='productiondefect',
            name='material_raw_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='defect_needs', to='inventory.rawmaterial', verbose_name='مادهٔ جایگزین'),
        ),
        migrations.AddField(
            model_name='productiondefect',
            name='material_work_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ کاریِ تحویل'),
        ),
        migrations.AddField(
            model_name='productiondefect',
            name='material_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defect_material_needs', to=settings.AUTH_USER_MODEL, verbose_name='کارگرِ انجام\u200cدهندهٔ جبران'),
        ),
    ]
