# Generated by Django 5.2.11 on 2026-09-10 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_painting_material_requirement'),
        ('product', '0018_productiondefect'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaintingMaterialRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption_per_unit', models.DecimalField(decimal_places=3, default=0, help_text='مثال: ۰.۰۵ لیتر رنگ به ازای هر عدد محصول در این مرحله', max_digits=10, verbose_name='مقدار مصرف به ازای هر واحد محصول')),
                ('painting_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_requirements', to='product.paintingstage', verbose_name='مرحله نقاشی')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='painting_requirements', to='inventory.rawmaterial', verbose_name='ماده اولیه')),
            ],
            options={
                'verbose_name': 'فرمول مصرف مواد نقاشی',
                'verbose_name_plural': 'فرمول\u200cهای مصرف مواد نقاشی',
                'ordering': ['painting_stage__process__name', 'painting_stage__order', 'raw_material__name'],
                'unique_together': {('painting_stage', 'raw_material')},
            },
        ),
    ]
