# Generated by Django 5.2.11 on 2026-10-05 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_productiondefect_material_quantity_and_more'),
        ('storefront', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='storefront.address', verbose_name='آدرس انتخاب\u200cشده'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='تخفیف'),
        ),
        migrations.AddField(
            model_name='order',
            name='final_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مبلغ نهایی'),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(blank=True, verbose_name='آدرس ارسال نهایی'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مبلغ کل'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='کد رهگیری'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ارتفاع سفارشی (سانتی\u200cمتر)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='length',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='طول سفارشی (سانتی\u200cمتر)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='عرض سفارشی (سانتی\u200cمتر)'),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ارتفاع پیش\u200cفرض (سانتی\u200cمتر)'),
        ),
        migrations.AddField(
            model_name='product',
            name='height_editable',
            field=models.BooleanField(default=True, verbose_name='امکان تغییر ارتفاع توسط مشتری'),
        ),
        migrations.AddField(
            model_name='product',
            name='height_price_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد افزایش قیمت به ازای هر سانتی\u200cمتر ارتفاع'),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='طول پیش\u200cفرض (سانتی\u200cمتر)'),
        ),
        migrations.AddField(
            model_name='product',
            name='length_editable',
            field=models.BooleanField(default=True, verbose_name='امکان تغییر طول توسط مشتری'),
        ),
        migrations.AddField(
            model_name='product',
            name='length_price_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد افزایش قیمت به ازای هر سانتی\u200cمتر طول'),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='عرض پیش\u200cفرض (سانتی\u200cمتر)'),
        ),
        migrations.AddField(
            model_name='product',
            name='width_editable',
            field=models.BooleanField(default=True, verbose_name='امکان تغییر عرض توسط مشتری'),
        ),
        migrations.AddField(
            model_name='product',
            name='width_price_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد افزایش قیمت به ازای هر سانتی\u200cمتر عرض'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('planned', 'برنامه\u200cریزی شده'), ('producing', 'در حال تولید'), ('completed', 'تکمیل شده'), ('paid', 'پرداخت شده'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل داده شده'), ('cancelled', 'لغو شده')], default='draft', max_length=20, verbose_name='وضعیت سفارش'),
        ),
    ]
