# Generated by Django 5.2.11 on 2026-09-12 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_painting_material_requirement'),
        ('product', '0019_painting_material_requirement'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paintingmaterialrequirement',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='paintingmaterialrequirement',
            name='product',
            field=models.ForeignKey(blank=True, help_text='اگر خالی باشد، این فرمول برای همه محصولاتی که از این مرحله عبور می\u200cکنند اعمال می\u200cشود. اگر محصول مشخصی انتخاب شود، فقط برای همان محصول این نرخ مصرف جایگزین نرخ پیش\u200cفرض مرحله می\u200cشود.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='painting_material_overrides', to='product.product', verbose_name='محصول (برای Override اختصاصی — خالی = پیش\u200cفرض همه محصولات)'),
        ),
        migrations.AddConstraint(
            model_name='paintingmaterialrequirement',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', True)), fields=('painting_stage', 'raw_material'), name='unique_default_requirement_per_stage_material'),
        ),
        migrations.AddConstraint(
            model_name='paintingmaterialrequirement',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('painting_stage', 'raw_material', 'product'), name='unique_product_override_per_stage_material'),
        ),
    ]
