# Generated by Django 5.2.11 on 2026-09-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_painting_material_requirement'),
        ('product', '0020_add_product_override_to_painting_material_requirement'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paintingmaterialrequirement',
            name='unique_default_requirement_per_stage_material',
        ),
        migrations.RemoveConstraint(
            model_name='paintingmaterialrequirement',
            name='unique_product_override_per_stage_material',
        ),
        migrations.AddField(
            model_name='paintingmaterialrequirement',
            name='color_part',
            field=models.CharField(blank=True, choices=[('بدنه', 'بدنه'), ('درب', 'درب'), ('دستگیره', 'دستگیره'), ('پایه', 'پایه'), ('صفحه', 'صفحه'), ('رینگ', 'رینگ')], help_text='اگر خالی باشد و product هم خالی باشد → پیش\u200cفرض سطح مرحله برای همه. اگر product پر و color_part خالی باشد → override برای کل محصول در همه بخش\u200cهای رنگی آن. اگر هر دو پر باشند → override فقط برای همین بخش رنگی خاص همین محصول.', max_length=20, null=True, verbose_name='بخش رنگی (برای Override اختصاصی به یک بخش خاص محصول)'),
        ),
        migrations.AddConstraint(
            model_name='paintingmaterialrequirement',
            constraint=models.UniqueConstraint(condition=models.Q(('color_part__isnull', True), ('product__isnull', True)), fields=('painting_stage', 'raw_material'), name='unique_default_requirement_per_stage_material'),
        ),
        migrations.AddConstraint(
            model_name='paintingmaterialrequirement',
            constraint=models.UniqueConstraint(condition=models.Q(('color_part__isnull', True), ('product__isnull', False)), fields=('painting_stage', 'raw_material', 'product'), name='unique_product_override_per_stage_material'),
        ),
        migrations.AddConstraint(
            model_name='paintingmaterialrequirement',
            constraint=models.UniqueConstraint(condition=models.Q(('color_part__isnull', False), ('product__isnull', False)), fields=('painting_stage', 'raw_material', 'product', 'color_part'), name='unique_product_colorpart_override_per_stage_material'),
        ),
    ]
