# Generated by Django 5.2.11 on 2026-10-05 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_custodyconsumption_custody_return_and_more'),
        ('product', '0023_product_slug_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paintingmaterialrequirement',
            options={'ordering': ['product__name', 'color_part', 'process__name', 'stage__order', 'raw_material__name'], 'verbose_name': 'فرمول مصرف مواد نقاشی', 'verbose_name_plural': 'فرمول\u200cهای مصرف مواد نقاشی'},
        ),
        migrations.AlterUniqueTogether(
            name='paintingmaterialrequirement',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='paintingmaterialrequirement',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_requirements', to='product.paintingstage', verbose_name='مرحله نقاشی'),
        ),
        migrations.AlterUniqueTogether(
            name='paintingmaterialrequirement',
            unique_together={('process', 'stage', 'raw_material', 'product', 'color_part')},
        ),
    ]
