# Generated by Django 5.2.11 on 2026-10-06 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_dailymaterialqueue_options_and_more'),
        ('product', '0024_alter_paintingmaterialrequirement_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paintingprocessmaterial',
            options={'ordering': ['process__name', 'stage__order', 'raw_material__name'], 'verbose_name': 'ماده اولیه کاتالوگ روند', 'verbose_name_plural': 'مواد اولیه کاتالوگ روندها'},
        ),
        migrations.AlterUniqueTogether(
            name='paintingprocessmaterial',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='paintingprocessmaterial',
            name='stage',
            field=models.ForeignKey(blank=True, help_text='اگر مشخص شود، این ماده فقط برای این مرحله در صف روزانه انبار ظاهر می\u200cشود.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_materials', to='product.paintingstage', verbose_name='مرحله نقاشی'),
        ),
        migrations.AlterUniqueTogether(
            name='paintingprocessmaterial',
            unique_together={('process', 'raw_material', 'stage')},
        ),
    ]
