# Generated by Django 5.2.11 on 2026-10-06 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_alter_discount_updated_at'),
        ('product', '0025_add_stage_to_painting_processmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='discounts.discount', verbose_name='تخفیف'),
        ),
    ]
