# Generated by Django 5.2.11 on 2026-10-01 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('last_activity_at', models.DateTimeField(auto_now=True, verbose_name='آخرین فعالیت')),
                ('provider', models.CharField(blank=True, max_length=32, verbose_name='ارائه\u200cدهنده')),
                ('model', models.CharField(blank=True, max_length=64, verbose_name='مدل')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'گفتگوی دستیار هوشمند',
                'verbose_name_plural': 'گفتگوهای دستیار هوشمند',
                'ordering': ['-last_activity_at'],
            },
        ),
        migrations.CreateModel(
            name='AIConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'کاربر'), ('assistant', 'دستیار')], max_length=16, verbose_name='نقش')),
                ('content', models.TextField(verbose_name='متن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='craftflow_ai.aiconversation', verbose_name='گفتگو')),
            ],
            options={
                'verbose_name': 'پیام دستیار هوشمند',
                'verbose_name_plural': 'پیام\u200cهای دستیار هوشمند',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='شناسهٔ گفتگو')),
                ('tool_name', models.CharField(db_index=True, max_length=64, verbose_name='ابزار')),
                ('arguments', models.JSONField(blank=True, default=dict, verbose_name='آرگومان\u200cها')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='نتیجه')),
                ('status', models.CharField(choices=[('completed', 'موفق'), ('failed', 'ناموفق'), ('denied', 'رد شد (دسترسی)')], default='completed', max_length=16, verbose_name='وضعیت')),
                ('error_code', models.CharField(blank=True, max_length=48, verbose_name='کد خطا')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='مدت (میلی\u200cثانیه)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'رد ممیزی هوش مصنوعی',
                'verbose_name_plural': 'ردهای ممیزی هوش مصنوعی',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tool_name', 'created_at'], name='craftflow_a_tool_na_3a010a_idx'), models.Index(fields=['user', 'created_at'], name='craftflow_a_user_id_633312_idx')],
            },
        ),
    ]
