# Generated by Django 5.2.11 on 2026-09-16 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0005_remove_workerprofile_skill_costs_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام ماده اولیه')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='کد')),
                ('unit', models.CharField(choices=[('kg', 'کیلوگرم'), ('lit', 'لیتر'), ('pcs', 'عدد'), ('m', 'متر')], max_length=10, verbose_name='واحد')),
                ('min_stock_alert', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='حداقل موجودی هشدار')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'ماده اولیه',
                'verbose_name_plural': 'مواد اولیه',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RawMaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام دسته')),
            ],
            options={
                'verbose_name': 'دسته مواد اولیه',
                'verbose_name_plural': 'دسته\u200cهای مواد اولیه',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام تامین\u200cکننده')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'تامین\u200cکننده',
                'verbose_name_plural': 'تامین\u200cکنندگان',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('ordered', 'سفارش\u200cشده'), ('received', 'دریافت\u200cشده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('note', models.TextField(blank=True, verbose_name='یادداشت')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.supplier', verbose_name='تامین\u200cکننده')),
            ],
            options={
                'verbose_name': 'سفارش خرید',
                'verbose_name_plural': 'سفارشات خرید',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مقدار')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت واحد (ریال)')),
                ('received_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مقدار دریافت\u200cشده')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchaseorder', verbose_name='سفارش خرید')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.rawmaterial', verbose_name='ماده اولیه')),
            ],
            options={
                'verbose_name': 'آیتم سفارش خرید',
                'verbose_name_plural': 'آیتم\u200cهای سفارش خرید',
                'ordering': ['purchase_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='inventory.rawmaterialcategory', verbose_name='دسته'),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('purchase', 'خرید/ورود'), ('consumption', 'مصرف'), ('adjustment', 'اصلاحیه'), ('return', 'مرجوعی')], max_length=20, verbose_name='نوع حرکت')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مقدار')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='قیمت واحد (ریال)')),
                ('reference_color_part', models.CharField(blank=True, max_length=20, verbose_name='بخش رنگی')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('catalog_raw_material', models.ForeignKey(blank=True, help_text='برای مصرف نقاشی، ماده کاتالوگ اصلی را مستقل از ماده واقعی رنگ نگه می\u200cدارد.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_consumption_movements', to='inventory.rawmaterial', verbose_name='ماده اولیه کاتالوگ')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.rawmaterial', verbose_name='ماده اولیه')),
                ('reference_order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paint_material_movements', to='product.orderitem', verbose_name='آیتم سفارش (برای نقاشی)')),
                ('reference_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productiontask', verbose_name='وظیفه تولید مرتبط')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier', verbose_name='تامین\u200cکننده')),
            ],
            options={
                'verbose_name': 'حرکت انبار',
                'verbose_name_plural': 'حرکات انبار',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='rawmaterial',
            unique_together={('category', 'name')},
        ),
    ]
