# Generated by Django 5.2.11 on 2026-09-13 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='catalog_raw_material',
            field=models.ForeignKey(blank=True, help_text='برای مصرف نقاشی، ماده کاتالوگ اصلی را مستقل از ماده واقعی رنگ نگه می\u200cدارد.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_consumption_movements', to='inventory.rawmaterial', verbose_name='ماده اولیه کاتالوگ'),
        ),
    ]
