# Generated by Django 5.2.11 on 2026-09-10 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('product', '0018_productiondefect'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مقدار مورد نیاز')),
                ('issued_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مقدار تحویل شده')),
                ('purpose', models.CharField(choices=[('production', 'برنامه تولید'), ('rework', 'جبران خرابی / ساخت مجدد')], default='production', max_length=20, verbose_name='علت درخواست')),
                ('status', models.CharField(choices=[('requested', 'در انتظار تحویل'), ('issued', 'تحویل شده'), ('cancelled', 'لغو شده')], default='requested', max_length=20, verbose_name='وضعیت')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان درخواست')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تحویل')),
                ('defect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_issues', to='product.productiondefect', verbose_name='گزارش خرابی')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_material_issues', to=settings.AUTH_USER_MODEL, verbose_name='تحویل دهنده')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='inventory.rawmaterial', verbose_name='ماده اولیه')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_material_issues', to=settings.AUTH_USER_MODEL, verbose_name='درخواست کننده')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_issues', to='product.productiontask', verbose_name='تسک تولید')),
            ],
            options={
                'verbose_name': 'درخواست تحویل مواد',
                'verbose_name_plural': 'درخواست\u200cهای تحویل مواد',
                'ordering': ['status', '-created_at'],
            },
        ),
    ]
