# Generated by Django 5.2.11 on 2026-09-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_materialissue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialissue',
            name='status',
            field=models.CharField(choices=[('requested', 'در انتظار تحویل'), ('partial', 'تحویل ناقص'), ('issued', 'تحویل شده'), ('cancelled', 'لغو شده')], default='requested', max_length=20, verbose_name='وضعیت'),
        ),
    ]
