# Generated by Django 5.2.11 on 2026-09-19 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_material_issue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-created_at'], 'verbose_name': 'گردش انبار', 'verbose_name_plural': 'گردش انبار'},
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='pack_size',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='مثلاً قوطی ۴ لیتری = 4. صفر یعنی بسته\u200cبندی ثابت ندارد و مقدار دقیق تحویل داده می\u200cشود.', max_digits=10, verbose_name='حجم/وزن هر بسته'),
        ),
        migrations.AlterField(
            model_name='materialissue',
            name='stock_movement',
            field=models.OneToOneField(blank=True, help_text='گردش انبار مصرفی که این درخواست را تسویه کرده است.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_issue', to='inventory.stockmovement', verbose_name='گردش انبار ثبت\u200cشده'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='catalog_raw_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_consumption_movements', to='inventory.rawmaterial', verbose_name='ماده اولیه '),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('purchase', 'خرید/ورود'), ('consumption', 'مصرف'), ('adjustment', 'اصلاحیه'), ('return', 'مرجوعی')], max_length=20, verbose_name='نوع'),
        ),
        migrations.CreateModel(
            name='MaterialHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان تحویل')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_handovers', to=settings.AUTH_USER_MODEL, verbose_name='تحویل\u200cدهنده (انبار)')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_handovers', to=settings.AUTH_USER_MODEL, verbose_name='تحویل\u200cگیرنده')),
            ],
            options={
                'verbose_name': 'سند تحویل مواد',
                'verbose_name_plural': 'اسناد تحویل مواد',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='materialissue',
            name='handover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='inventory.materialhandover', verbose_name='آخرین سند تحویل'),
        ),
        migrations.CreateModel(
            name='MaterialHandoverLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='جمع مورد نیاز')),
                ('leftover_used', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='کسر از باقی\u200cماندهٔ سالن')),
                ('from_stock_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='خروج فیزیکی از انبار')),
                ('pack_size', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='حجم هر بسته (در زمان تحویل)')),
                ('packs_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بسته/قوطی')),
                ('leftover_before', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='باقی\u200cمانده قبل از تحویل')),
                ('leftover_after', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='باقی\u200cمانده بعد از تحویل')),
                ('handover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.materialhandover', verbose_name='سند تحویل')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handover_lines', to='inventory.rawmaterial', verbose_name='ماده اولیه')),
            ],
            options={
                'verbose_name': 'ردیف سند تحویل',
                'verbose_name_plural': 'ردیف\u200cهای سند تحویل',
                'ordering': ['handover', 'raw_material__name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialLeftover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مقدار باقی\u200cمانده در سالن')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('raw_material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leftover', to='inventory.rawmaterial', verbose_name='ماده اولیه')),
            ],
            options={
                'verbose_name': 'باقی\u200cماندهٔ سالن تولید',
                'verbose_name_plural': 'باقی\u200cماندهٔ سالن تولید',
            },
        ),
    ]
