# Generated by Django 5.2.11 on 2026-09-13 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockmovement_catalog_raw_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialissue',
            name='stock_movement',
            field=models.OneToOneField(blank=True, help_text='حرکت انبار مصرفی که این درخواست را تسویه کرده است.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_issue', to='inventory.stockmovement', verbose_name='حرکت انبار ثبت\u200cشده'),
        ),
    ]
