# Generated by Django 6.0.6 on 2026-09-14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_materialissue_stock_movement_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialissue',
            name='packaging_unit',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='material_issues',
                to='product.packagingunit',
                verbose_name='واحد بسته‌بندی',
            ),
        ),
    ]
