# Generated by Django 5.2.11 on 2026-09-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_handover_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='بارکد'),
        ),
    ]
