# Generated by Django 5.2.11 on 2026-09-26 10:00

import django.db.models.deletion
from django.db import migrations, models


def copy_old_links(apps, schema_editor):
    """انتقال لینک یک‌به‌یک قدیمی (MaterialIssue.stock_movement) به FK جدیدِ سمت حرکت انبار."""
    MaterialIssue = apps.get_model('inventory', 'MaterialIssue')
    StockMovement = apps.get_model('inventory', 'StockMovement')
    for issue in MaterialIssue.objects.exclude(stock_movement_id=None).iterator():
        StockMovement.objects.filter(pk=issue.stock_movement_id).update(
            fulfilled_issue_id=issue.pk,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rawmaterial_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='fulfilled_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.materialissue', verbose_name='درخواست مرتبط'),
        ),
        migrations.RunPython(copy_old_links, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='materialissue',
            name='stock_movement',
        ),
    ]
