# Generated by Django 5.2.11 on 2026-09-14 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_materialissue_packaging_unit'),
        ('product', '0011_add_defect_packaging_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='materialissue',
            name='color_part',
            field=models.CharField(blank=True, max_length=20, verbose_name='بخش رنگی'),
        ),
        migrations.AddField(
            model_name='materialissue',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_issues', to='product.orderitem', verbose_name='آیتم سفارش'),
        ),
        migrations.AddField(
            model_name='materialissue',
            name='painting_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_issues', to='product.paintingprocess', verbose_name='روند نقاشی'),
        ),
        migrations.AddField(
            model_name='materialissue',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_material_issues', to=settings.AUTH_USER_MODEL, verbose_name='تحویل گیرنده'),
        ),
    ]
