# Generated by Django 5.2.11 on 2026-09-14 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_materialissue_color_part_materialissue_order_item_and_more'),
        ('product', '0011_add_defect_packaging_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='reference_color_part',
            field=models.CharField(blank=True, max_length=20, verbose_name='بخش رنگی'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='reference_order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paint_material_movements', to='product.orderitem', verbose_name='آیتم سفارش (برای نقاشی)'),
        ),
    ]
