# Generated by Django 5.2.11 on 2026-10-01 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stock_movement_fulfilled_issue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCustody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مقدار باقی\u200cمانده نزد کارگر')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('held_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_custodies', to=settings.AUTH_USER_MODEL, verbose_name='تحویل\u200cگیرنده (نقاش)')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custodies', to='inventory.rawmaterial', verbose_name='ماده اولیه')),
            ],
            options={
                'verbose_name': 'امانت مواد نزد کارگر',
                'verbose_name_plural': 'امانت\u200cهای مواد نزد کارگران',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialCustodyReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مقدار توزین\u200cشده')),
                ('quantity_before', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='موجودی امانت قبل')),
                ('delta', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='اختلاف')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('custody', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='inventory.materialcustody', verbose_name='امانت')),
                ('held_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_custody_returns', to=settings.AUTH_USER_MODEL, verbose_name='کارگر')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custody_returns', to='inventory.rawmaterial', verbose_name='ماده اولیه')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_custody_returns', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده (انبار)')),
            ],
            options={
                'verbose_name': 'سند بازگشت امانت',
                'verbose_name_plural': 'اسناد بازگشت امانت',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='materialcustody',
            constraint=models.UniqueConstraint(fields=('raw_material', 'held_by'), name='uniq_material_custody_raw_held_by'),
        ),
    ]
