# Generated by Django 5.2.11 on 2026-10-01 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_materialcustody_materialcustodyreturn_and_more'),
        ('product', '0018_productcategory_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='materialcustodyreturn',
            name='warehouse_return',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مقدار بازگشتی فیزیکی به انبار'),
        ),
        migrations.CreateModel(
            name='CustodyConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مقدار مصرف\u200cشده')),
                ('custody_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='inventory.materialcustodyreturn', verbose_name='سند بازگشت امانت')),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custody_consumptions', to='product.productiondefect', verbose_name='خرابی')),
                ('held_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custody_consumptions', to=settings.AUTH_USER_MODEL, verbose_name='کارگر')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custody_consumptions', to='inventory.rawmaterial', verbose_name='ماده اولیه')),
            ],
            options={
                'verbose_name': 'انتساب مصرف امانت',
                'verbose_name_plural': 'انتساب\u200cهای مصرف امانت',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('custody_return', 'defect'), name='uniq_custody_consumption_return_defect'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='custody_consumption_quantity_positive')],
            },
        ),
    ]
