# Generated by Django 5.2.11 on 2026-10-01 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_materialcustodyreturn_warehouse_return_and_more'),
        ('product', '0018_productcategory_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMaterialQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(verbose_name='تاریخ کاری')),
                ('planned_quantity', models.DecimalField(decimal_places=2, default=0, help_text='Snapshot نیازی که از برنامهٔ نقاشی گرفته شده است.', max_digits=12, verbose_name='نیاز برنامه\u200cریزی\u200cشده (امروز)')),
                ('delivered_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='تحویل شده')),
                ('returned_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='برگشتی')),
                ('actual_consumption', models.DecimalField(decimal_places=2, default=0, help_text='delivered_quantity - returned_quantity', max_digits=12, verbose_name='مصرف واقعی')),
                ('excess_consumption', models.DecimalField(decimal_places=2, default=0, help_text='max(0, actual_consumption - planned_quantity)', max_digits=12, verbose_name='مصرف اضافه')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تحویل'), ('delivered', 'تحویل شده'), ('returned', 'برگشت ثبت شده'), ('closed', 'پایان روز بسته شد'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_queues', to='inventory.rawmaterial', verbose_name='ماده اولیه')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_material_queues', to=settings.AUTH_USER_MODEL, verbose_name='کارگر')),
            ],
            options={
                'verbose_name': 'صف مواد روزانه',
                'verbose_name_plural': 'صف\u200cهای مواد روزانه',
                'ordering': ['work_date', 'worker', 'raw_material'],
            },
        ),
        migrations.CreateModel(
            name='DailyMaterialQueueSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='سهم از این منبع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('painting_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_queue_sources', to='product.paintingstage', verbose_name='مرحله نقاشی')),
                ('production_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_queue_sources', to='product.productiontask', verbose_name='تسک تولید')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='inventory.dailymaterialqueue', verbose_name='صف روزانه')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_queue_sources', to='inventory.rawmaterial', verbose_name='ماده اولیه')),
            ],
            options={
                'verbose_name': 'منبع صف روزانه',
                'verbose_name_plural': 'منابع صف\u200cهای روزانه',
                'ordering': ['queue', 'production_task'],
            },
        ),
        migrations.AddIndex(
            model_name='dailymaterialqueue',
            index=models.Index(fields=['work_date', 'worker'], name='inventory_d_work_da_1618d4_idx'),
        ),
        migrations.AddIndex(
            model_name='dailymaterialqueue',
            index=models.Index(fields=['work_date', 'status'], name='inventory_d_work_da_bb3123_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailymaterialqueue',
            unique_together={('work_date', 'worker', 'raw_material')},
        ),
        migrations.AlterUniqueTogether(
            name='dailymaterialqueuesource',
            unique_together={('queue', 'production_task', 'painting_stage', 'raw_material')},
        ),
    ]
