# Generated by Django 5.2.11 on 2026-10-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_dailymaterialqueue_dailymaterialqueuesource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymaterialqueue',
            name='conflict_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='شرح تعارض'),
        ),
        migrations.AddField(
            model_name='dailymaterialqueue',
            name='has_plan_conflict',
            field=models.BooleanField(default=False, help_text='وقتی برنامهٔ نقاشی بعد از تحویل/برگشت تغییر کند، موجودی و تاریخچهٔ واقعی دست\u200cنخورده می\u200cماند و فقط این پرچم فعال می\u200cشود.', verbose_name='تعارض برنامه با تراکنش'),
        ),
    ]
