# Generated by Django 5.2.11 on 2026-10-02 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_dailymaterialqueue_conflict_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMaterialClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(unique=True, verbose_name='تاریخ کاری')),
                ('status', models.CharField(choices=[('confirmed', 'روز بررسی و تأیید شد')], default='confirmed', max_length=20, verbose_name='وضعیت')),
                ('closed_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان تأیید')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='یادداشت')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_material_closings', to=settings.AUTH_USER_MODEL, verbose_name='تأییدکننده')),
            ],
            options={
                'verbose_name': 'تأیید پایان روز',
                'verbose_name_plural': 'تأیید پایان روزها',
                'ordering': ['-work_date'],
            },
        ),
    ]
