# Generated by Django 5.2.11 on 2026-10-05 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_custodyconsumption_custody_return_and_more'),
        ('product', '0024_alter_paintingmaterialrequirement_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailymaterialqueue',
            options={'ordering': ['work_date', 'worker', 'raw_material', 'painting_stage'], 'verbose_name': 'ردیف صف مواد روزانه', 'verbose_name_plural': 'صف\u200cهای مواد روزانه'},
        ),
        migrations.AlterUniqueTogether(
            name='dailymaterialqueue',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dailymaterialqueue',
            name='painting_stage',
            field=models.ForeignKey(blank=True, help_text='مرحله نقاشی که این ردیف صف مربوط به آن است (برای ردیابی تفکیک شده).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_queues', to='product.paintingstage', verbose_name='مرحله نقاشی'),
        ),
        migrations.AlterUniqueTogether(
            name='dailymaterialqueue',
            unique_together={('work_date', 'worker', 'raw_material', 'painting_stage')},
        ),
        migrations.AddIndex(
            model_name='dailymaterialqueue',
            index=models.Index(fields=['work_date', 'painting_stage'], name='inventory_d_work_da_c9d77d_idx'),
        ),
    ]
