# Generated by Django 5.2.11 on 2026-10-06 06:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_dailymaterialqueue_options_and_more'),
        ('product', '0024_alter_paintingmaterialrequirement_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailymaterialqueue',
            options={'ordering': ['work_date', 'worker', 'raw_material', 'painting_stage', 'color_part'], 'verbose_name': 'ردیف صف مواد روزانه', 'verbose_name_plural': 'صف\u200cهای مواد روزانه'},
        ),
        migrations.AlterUniqueTogether(
            name='dailymaterialqueue',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dailymaterialqueue',
            name='color_part',
            field=models.CharField(blank=True, help_text='بخش رنگی (مثلاً بدنه، درب) برای تفکیک نیازهای هم\u200cمرحله.', max_length=50, verbose_name='بخش رنگی'),
        ),
        migrations.AlterUniqueTogether(
            name='dailymaterialqueue',
            unique_together={('work_date', 'worker', 'raw_material', 'painting_stage', 'color_part')},
        ),
    ]
