# Generated by Django 5.2.11 on 2026-10-08 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_partial_and_carryover'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymaterialclosing',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان قفل'),
        ),
        migrations.AddField(
            model_name='dailymaterialclosing',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_material_locks', to=settings.AUTH_USER_MODEL, verbose_name='قفل\u200cکننده'),
        ),
        migrations.AlterField(
            model_name='dailymaterialclosing',
            name='status',
            field=models.CharField(choices=[('confirmed', 'روز بررسی و تأیید شد'), ('locked', 'قفل شده — تغییرات ممنوع')], default='confirmed', max_length=20, verbose_name='وضعیت'),
        ),
    ]
