# Generated by Django 5.2.11 on 2026-10-08 12:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_add_lock_fields_to_closing'),
        ('product', '0026_order_discount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ شمارش')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('approved', 'تأیید شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تأیید')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='یادداشت')),
            ],
            options={
                'verbose_name': 'سند شمارش انبار',
                'verbose_name_plural': 'سندهای شمارش انبار',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_quantity', models.DecimalField(decimal_places=2, help_text='موجودی محاسبه\u200cشده توسط سیستم در لحظه شمارش.', max_digits=12, verbose_name='موجودی سیستم')),
                ('counted_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='تعداد شمرده شده')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='یادداشت خط')),
            ],
            options={
                'verbose_name': 'خط شمارش انبار',
                'verbose_name_plural': 'خطوط شمارش انبار',
                'ordering': ['raw_material__category', 'raw_material__name'],
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='reverses',
            field=models.ForeignKey(blank=True, help_text='برای purchase_reversal: حرکت purchase اصلی که ابطال می\u200cشود.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='inventory.stockmovement', verbose_name='ابطال\u200cکننده'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('purchase', 'خرید/ورود'), ('consumption', 'مصرف (تحویل به تولید)'), ('return', 'مرجوعی از تولید'), ('adjustment', 'اصلاحیه (افزایش)'), ('adjust_out', 'اصلاحیه (کاهش)'), ('purchase_reversal', 'ابطال خرید/ورود'), ('stock_count', 'اصلاح شمارش انبار')], max_length=20, verbose_name='نوع'),
        ),
        migrations.AddConstraint(
            model_name='dailymaterialqueuesource',
            constraint=models.UniqueConstraint(fields=('queue', 'kind', 'production_task', 'painting_stage', 'defect', 'carryover_from', 'raw_material'), name='unique_queue_source_identifiers'),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_counts_approved', to=settings.AUTH_USER_MODEL, verbose_name='تأییدکننده'),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_counts_created', to=settings.AUTH_USER_MODEL, verbose_name='شمارش\u200cکننده'),
        ),
        migrations.AddField(
            model_name='stockcountline',
            name='raw_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_count_lines', to='inventory.rawmaterial', verbose_name='ماده اولیه'),
        ),
        migrations.AddField(
            model_name='stockcountline',
            name='stock_count',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockcount', verbose_name='سند شمارش'),
        ),
        migrations.AlterUniqueTogether(
            name='stockcountline',
            unique_together={('stock_count', 'raw_material')},
        ),
    ]
