# Generated by Django 5.2.11 on 2026-10-10 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_stockcount_stockcountline_stockmovement_reverses_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMaterialHandout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(verbose_name='تاریخ کاری')),
                ('delivered_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مجموع تحویل شده')),
                ('weighed_remaining', models.DecimalField(blank=True, decimal_places=2, help_text='null = هنوز توزین نشده. صفر = بسته کامل مصرف شده.', max_digits=12, null=True, verbose_name='باقی\u200cمانده وزن\u200cشده')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='اولین تحویل')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_material_handouts', to='inventory.rawmaterial', verbose_name='ماده اولیه')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_material_handouts', to=settings.AUTH_USER_MODEL, verbose_name='کارگر')),
            ],
            options={
                'verbose_name': 'تحویل مواد روزانه',
                'verbose_name_plural': 'تحویل\u200cهای مواد روزانه',
                'ordering': ['-work_date', 'worker', 'raw_material'],
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='handout',
            field=models.ForeignKey(blank=True, help_text='حرکت\u200cهای تحویل/بازگشتِ جدید به این سند تحویل وصل می\u200cشوند.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.dailymaterialhandout', verbose_name='تحویل روزانه'),
        ),
        migrations.AddIndex(
            model_name='dailymaterialhandout',
            index=models.Index(fields=['work_date', 'worker'], name='inventory_d_work_da_773582_idx'),
        ),
        migrations.AddIndex(
            model_name='dailymaterialhandout',
            index=models.Index(fields=['work_date', 'weighed_remaining'], name='inventory_d_work_da_dd6dd0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailymaterialhandout',
            unique_together={('work_date', 'worker', 'raw_material')},
        ),
    ]
