"""
Django settings for selvi project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config, Csv
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!


DEBUG = config('DEBUG', default=True, cast=bool)
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='selvichoob.ir,45.159.149.122,localhost,127.0.0.1', cast=Csv())
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='https://selvichoob.ir', cast=Csv())






# QR Settings
# QR_DOMAIN = '192.168.1.201:8000'  # یا '127.0.0.1:8000' برای تست
# QR_PROTOCOL = 'http'  # یا 'http'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'product',
    'inventory',
    'craftflow_ai',
    'storefront',
    'cart',
    'discounts',
    'payments',
    'accounts',
    'api',
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_spectacular',
    'django.contrib.humanize',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'selvi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.cart_totals',
            ],
        },
    },
]

WSGI_APPLICATION = 'selvi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            'timeout': 20,
            'transaction_mode': 'IMMEDIATE',
            'init_command': 'PRAGMA journal_mode=WAL;',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [BASE_DIR/"static"]

STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage'},
}


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/shop/'
LOGOUT_REDIRECT_URL = '/shop/'


STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = config('MEDIA_ROOT', default='/root/selvi/selvi/media')





# INSTALLED_APPS = [
#     # ...
#     'rest_framework',
# ]

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': None,
}


# مسیر پوشه‌ای که فایل‌های CNC در آن ذخیره شده‌اند
# CNC_SOURCE_DIR = r'C:\cnc_archive'  
CNC_SOURCE_DIR = BASE_DIR /  'cnc_archive'  
CNC_FILE_EXTENSION = '.cnc'



# تنظیمات فایل‌های سوراخکاری (Drilling)
# DR_SOURCE_DIR = r'C:\dr_archive'        # پوشه فایل‌های XML سوراخکاری
DR_SOURCE_DIR = BASE_DIR /'dr_archive'

DR_FILE_EXTENSION = '.scx'              # پسوند فایل


# ===================================================================
#   لایهٔ هوش مصنوعی (CraftFlow AI Copilot) — فقط-خواندنی
#   همهٔ مقادیر از Environment Variable خوانده می‌شوند.
#   API Key را هرگز داخل گیت نگذارید؛ آن را در selvi/.env قرار دهید.
# ===================================================================
CRAFTFLOW_AI_ENABLED = config('CRAFTFLOW_AI_ENABLED', default=True, cast=bool)
CRAFTFLOW_AI_PROVIDER = config('CRAFTFLOW_AI_PROVIDER', default='gemini')
CRAFTFLOW_AI_MODEL = config('CRAFTFLOW_AI_MODEL', default='gemini-2.5-flash')
CRAFTFLOW_AI_API_KEY = config('CRAFTFLOW_AI_API_KEY', default='')
CRAFTFLOW_AI_BASE_URL = config('CRAFTFLOW_AI_BASE_URL', default='')
CRAFTFLOW_AI_MAX_TOOL_CALLS = config('CRAFTFLOW_AI_MAX_TOOL_CALLS', default=8, cast=int)
CRAFTFLOW_AI_TIMEOUT = config('CRAFTFLOW_AI_TIMEOUT', default=60, cast=int)
CRAFTFLOW_AI_MAX_HISTORY = config('CRAFTFLOW_AI_MAX_HISTORY', default=10, cast=int)
CRAFTFLOW_AI_TEMPERATURE = config('CRAFTFLOW_AI_TEMPERATURE', default=0.0, cast=float)

# نام گروه‌های مجاز برای هر دسترسی (همان گروه‌های موجود CraftFlow)
CRAFTFLOW_AI_MANAGER_GROUPS = config(
    'CRAFTFLOW_AI_MANAGER_GROUPS', default='1,2,3', cast=Csv())
CRAFTFLOW_AI_STAFF_GROUPS = config(
    'CRAFTFLOW_AI_STAFF_GROUPS', default='1', cast=Csv())
CRAFTFLOW_AI_WAREHOUSE_GROUPS = config(
    'CRAFTFLOW_AI_WAREHOUSE_GROUPS', default='انبار', cast=Csv())

# MCP Server shared secret for Hermes authentication
CRAFTFLOW_AI_MCP_SECRET = config('CRAFTFLOW_AI_MCP_SECRET', default='')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {'format': '[{asctime}] {levelname} {name}: {message}', 'style': '{'},
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'craftflow_ai': {
            'handlers': ['console'],
            'level': config('CRAFTFLOW_AI_LOG_LEVEL', default='INFO'),
            'propagate': False,
        },
    },
}

# --- REST Framework / API ---
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'CraftFlow Store API',
    'DESCRIPTION': 'API برای فروشگاه آنلاین و تولید سفارشات',
    'VERSION': '1.0.0',
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=2),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'AUTH_HEADER_TYPES': ('Bearer',),
}