# Generated by Django 5.2.11 on 2026-10-05 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0019_productiondefect_material_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, null=True, verbose_name='کلید جلسه')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سبد خرید',
                'verbose_name_plural': 'سبدهای خرید',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('custom_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='طول سفارشی (سانتی\u200cمتر)')),
                ('custom_width', models.PositiveIntegerField(blank=True, null=True, verbose_name='عرض سفارشی (سانتی\u200cمتر)')),
                ('custom_height', models.PositiveIntegerField(blank=True, null=True, verbose_name='ارتفاع سفارشی (سانتی\u200cمتر)')),
                ('unit_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت واحد')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart', verbose_name='سبد خرید')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'آیتم سبد خرید',
                'verbose_name_plural': 'آیتم\u200cهای سبد خرید',
            },
        ),
    ]
