# Generated by Django 5.2.11 on 2026-10-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='لوگو')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='عکس کاور')),
                ('site_name', models.CharField(default='فروشگاه', max_length=120, verbose_name='نام سایت')),
                ('hero_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان اصلی')),
                ('hero_subtitle', models.TextField(blank=True, verbose_name='زیرعنوان اصلی')),
                ('footer_text', models.TextField(blank=True, verbose_name='متن فوتر')),
                ('is_maintenance', models.BooleanField(default=False, verbose_name='در حالت تعمیرات')),
            ],
            options={
                'verbose_name': ' settings سایت',
                'verbose_name_plural': ' settings سایت',
            },
        ),
    ]
